parameters:
  - name: azureSubscription
    type: string

jobs:
  - deployment: Deploy
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: "Deploy resources using Bicep"
              inputs:
                azureSubscription: ${{parameters.azureSubscription}}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az deployment group create -f '13-Module.bicep' -g 'BicepWorkshopRG'