trigger: none

stages:
- stage: Deploy
  displayName: 'Deploy Bicep'
  jobs:
    - template: ./deploy.yaml
      parameters:
        deploymentEnvironment: stg
        azureSubscription: 'VS Enterprise – jramos@plainconcepts.com'        