trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deploy
  displayName: 'Deploy Bicep'
  jobs:
    - template: ./deploy.yaml
      parameters:
        azureSubscription: 'VS Enterprise – jramos@plainconcepts.com'        